// Code generated by baton-sdk/pkg/config. DO NOT EDIT.

package config

type Celigo struct {
	CeligoAccessToken string `mapstructure:"celigo-access-token"`
	Region            string `mapstructure:"region"`
}
